server.port=8081
spring.application.name=envio-service

# Database per Service — BD exclusiva de envio-service
spring.datasource.url=jdbc:h2:mem:envio_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-envio

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092

# URL sincrona a tarifa-service (Orquestacion)
tarifa.service.url=http://localhost:8082

# Topic Kafka (Coreografia)
kafka.topic.envio-creado=envio-creado
